var fs = require('fs');
var bt = String.fromCharCode(96);
var lines = [];
lines.push("import { useQuery } from '@tanstack/react-query';");
lines.push("import { apiGet, USE_MOCK_DATA } from '@/services/http';");
lines.push("import { withMockFallback } from '@/services/mock';");
lines.push("import { mockEvents } from '@/services/mock/events';");
lines.push("import type { Event, Timeline } from '@/types/api';");
lines.push("");
lines.push("const DEFAULT_LIMIT = 50;");
lines.push("");
lines.push("async function fetchEvents(limit = DEFAULT_LIMIT): Promise<{ events: Event[] }> {");
lines.push("  const params = new URLSearchParams({ limit: String(limit) });");
lines.push("  return apiGet<{ events: Event[] }>(" + bt + "/api/v1/events?$" + "{params.toString()}" + bt + ");");
lines.push("}");
lines.push("");
lines.push("export function useEvents(limit = DEFAULT_LIMIT) {");
lines.push("  return useQuery({");
lines.push("    queryKey: ['events', limit],");
lines.push("    queryFn: () =>");
lines.push("      withMockFallback(['events'], () => fetchEvents(limit),");
lines.push("        () => ({ events: mockEvents(limit) }),");
lines.push("        { enabled: USE_MOCK_DATA, isEmpty: (d) => d.events.length === 0 },");
lines.push("      ),");
lines.push("    refetchInterval: false,");
lines.push("  });");
lines.push("}");
lines.push("");
lines.push("export function useHostEvents(hostname, limit = 50) {");
lines.push("  return useQuery({");
lines.push("    queryKey: ['events', 'host', hostname, limit],");
lines.push("    queryFn: async () => {");
lines.push("      const params = new URLSearchParams({");
lines.push("        subject_id: hostname,");
lines.push("        subject_type: 'host',");
lines.push("        limit: String(limit),");
lines.push("      });");
lines.push("      const res = await apiGet<{ events: Event[] }>(" + bt + "/api/v1/events?$" + "{params.toString()}" + bt + ");");
lines.push("      return res.events;");
lines.push("    },");
lines.push("    enabled: !!hostname,");
lines.push("  });");
lines.push("}");
fs.writeFileSync('W:/sentinel/frontend/src/services/api/events.ts', lines.join('\n'));
console.log('Wrote events.ts');